# Python configuration
language: python
services: docker
python:
  - 3.7

before_install:
  - docker build --tag ml-blogs .

# Run project checker
script:
  - docker run --rm -it ml-blogs ./utils/check_project.sh
